export const root: string;
export const divider: string;
export const arrows: string;
export const column: string;
export const row: string;
export const dragging: string;
export const leading: string;
export const trailing: string;
export const collapsed: string;
