export const root: string;
export const combo: string;
export const container: string;
export const ok: string;
export const hidden: string;
export const btnInner: string;
export const label: string;
export const logo: string;
export const small: string;
